In [5]:
import numpy as np
arr1 = np.array([10,20,30,40])
print(arr1)
print(type(arr1))
arr2 = np.array([[10,20,30,40],[50,60,70,80]])
print(arr2)
print(type(arr2))

[10 20 30 40]
<class 'numpy.ndarray'>
[[10 20 30 40]
 [50 60 70 80]]
<class 'numpy.ndarray'>


In [6]:
#slicing of arr1
print(arr1[:3])
print(arr1[3:])
print(arr1[2:])

[10 20 30]
[40]
[30 40]


In [7]:
#slicing of arr2
print(arr2[:3,:3])
print(arr2[0,1:3])
print(arr2[1,2:4])

[[10 20 30]
 [50 60 70]]
[20 30]
[70 80]


In [8]:
#shape: number of rows and columns
print("Shape of arr1:", np.shape(arr1))
print("Shape of arr2:", np.shape(arr2))

#size: total number of elements
print("Size of arr1:", np.size(arr1))
print("Size of arr2:", np.size(arr2))

#dimension
print("Dimention of arr1:", np.ndim(arr1))
print("Dimention of arr2:", np.ndim(arr2))

#length:number of nested values
print("Length of arr1:", len(arr1))
print("length of arr2:", len(arr2))

Shape of arr1: (4,)
Shape of arr2: (2, 4)
Size of arr1: 4
Size of arr2: 8
Dimention of arr1: 1
Dimention of arr2: 2
Length of arr1: 4
length of arr2: 2


In [9]:
#datatype of variable
print(type(arr1))
print(type(arr2))

#datatype of array
print("Data type of arr1:", arr1.dtype)
print("Data type of arr2:", arr2.dtype)

#conversion of datatype
print(arr1.astype(float))
print(arr2.astype(float))
print(arr2.astype(str))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
Data type of arr1: int64
Data type of arr2: int64
[10. 20. 30. 40.]
[[10. 20. 30. 40.]
 [50. 60. 70. 80.]]
[['10' '20' '30' '40']
 ['50' '60' '70' '80']]


In [10]:
#mathematical operation
#addition
arr1 = np.array([40,50,10,30,40])
arr2 = np.array([20,10,20,60,10])
print(arr1+arr2)
print(np.add(arr1,arr2))
arr3 = np.array([[40,50],[30,40]])
arr4 = np.array([[20,10],[60,40]])
print(np.add(arr3,arr4))

#subtract
print(arr1-arr2)
print(np.subtract(arr3,arr4))

#division
print(arr1/arr2)
print(np.divide(arr3,arr4))


[60 60 30 90 50]
[60 60 30 90 50]
[[60 60]
 [90 80]]
[ 20  40 -10 -30  30]
[[ 20  40]
 [-30   0]]
[2.  5.  0.5 0.5 4. ]
[[2.  5. ]
 [0.5 1. ]]


In [11]:
#power
arr1 = np.array([4,5,1,3,2])
arr2 = np.array([2])
print(np.power(arr1,arr2))

#square root
arr1 = np.array([16,25,1,9,4])
print(np.sqrt(arr1))

[16 25  1  9  4]
[4. 5. 1. 3. 2.]


In [12]:
#join 
arr1 = np.array([10,20,30,40])
arr2 = np.array([30,50])
print(np.concatenate([arr1, arr2]))

arr3 = np.array([[10,20],[30,40]])
arr4 = np.array([[5,5],[3,3]])
print(np.concatenate([arr3, arr4],axis=1))

print(np.hstack([arr3,arr4]))     #horizontal concatenation
print(np.vstack([arr3,arr4]))     #vertical concatenation

[10 20 30 40 30 50]
[[10 20  5  5]
 [30 40  3  3]]
[[10 20  5  5]
 [30 40  3  3]]
[[10 20]
 [30 40]
 [ 5  5]
 [ 3  3]]


In [13]:
#split
arr = np.array([10,20,30,40,50,60])
print(np.array_split(arr,3))
print(np.array_split(arr,5))

[array([10, 20]), array([30, 40]), array([50, 60])]
[array([10, 20]), array([30]), array([40]), array([50]), array([60])]


In [14]:
#append
arr = np.array([[10,20],[30,40],[50,60]])
print(np.append(arr,[70,80]))   #(array,[value])

[10 20 30 40 50 60 70 80]


In [17]:
#insert
print(np.insert(arr,2,[90,100], axis=0))      #(array, index, [value])

[[ 10  20]
 [ 30  40]
 [ 90 100]
 [ 50  60]]


In [22]:
#delete
print(np.delete(arr,1,axis=0)) 
print(np.delete(arr,1,axis=1)) 

[[10 20]
 [50 60]]
[[10]
 [30]
 [50]]


In [31]:
#sort
ar = np.array([42,13,31,22,12])
print("Sorted array:", np.sort(ar))

#search
s = np.where(ar%2==0)
print(s)

#searchsorted
ss = np.searchsorted(np.sort(ar), 13)
print(ss)

Sorted array: [12 13 22 31 42]
(array([0, 3, 4]),)
1


In [35]:
#filter
fa = ar%3==0
new = ar[fa]
print(new)

[42 12]


In [39]:
#min max sum
print("Minimum:", np.min(ar))
print("Maximum:", np.max(ar))
print("Total:", np.sum(ar))

print("Size:", np.size(ar))
print("Mean:", np.mean(ar))
print("Commulative sum:", np.cumsum(ar))
print("Commulative product:", np.cumprod(ar))

Minimum: 12
Maximum: 42
Total: 120
Size: 5
Mean: 24.0
Commulative sum: [ 42  55  86 108 120]
Commulative product: [     42     546   16926  372372 4468464]


In [51]:
#to find total price
a = [100,150,120,300,250,200]
b = [10,50,40,30,50,20]

price = np.array(a)
quantity = np.array(b)

print(" Price:", price,"\n","Quantity:", quantity)
print()
c = np.cumprod([price,quantity], axis=0)
print("Total price:", c[1].sum())

 Price: [100 150 120 300 250 200] 
 Quantity: [10 50 40 30 50 20]

Total price: 38800


In [65]:
#statistical function
import statistics as stats
baked_food = [100,120,300,225,320,250,150,145]
a = np.array(baked_food)
print("Mean:", np.mean(baked_food))
print("Median:", np.median(baked_food))
print("Mode:", stats.mode(baked_food))
print("Standard deviation:", np.std(baked_food))
print("Variance:", np.var(baked_food))

Mean: 201.25
Median: 187.5
Mode: 100
Standard deviation: 78.61098841765062
Variance: 6179.6875


In [68]:
#comparing relationship
tobacco_consumption = [30,50,10,30,50,40]
deaths = [100,120,70,100,120,112]

print(np.corrcoef([tobacco_consumption,deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [69]:
price = [300,100,350,150,200]
sales= [10,20,7,17,3]

print(np.corrcoef([price,sales]))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
